### ISSUE TITLE
Add a @dfinity/info package that parses URL or otherwise and generate a ConnectionInfo object

### ISSUE THREAD

**Issue by hansl** [dfinity/agent-js#234]
```typescript
class ConnectionInfo {
  public static async fromWindow(): Promise<ConnectionInfo>;

  private constructor(public readonly canisterId: Principal, public readonly replicas: URL[]) {}
}
```

**Comment by krpeacock** [comment]
Is this still needed?

**Comment by hansl** [comment]
It could still be useful to have a library that parses the URL and get the canisterId for example. And then we can move that library to resolving DNS -> Canister Id when we have that technology.

**Comment by krpeacock** [comment]
Canister ID in URL is no longer a strong assumption. Closing this
