### ISSUE TITLE
The service worker should check for absence proofs and that the original is not in the tree during fallback.

### ISSUE THREAD

**Issue by jplevyak** [dfinity/agent-js#450]
**Is your feature request related to a problem? Please describe.**
The service worker should check for absence proofs to support 404.  It should also check that the original is not in the tree when it checks the fallback.

**Describe the solution you'd like**
Implement the above.

**Describe alternatives you've considered**

**Additional context**

**Comment by krpeacock** [comment]
Closing this because the serviceworker is no longer in this project
