### ISSUE TITLE
Create HttpAgent on back-end

### ISSUE THREAD

**Issue by fury02** [dfinity/agent-js#462]
I am trying to create (with initialization) HttpAgent -> const **httpAgent = new HttpAgent ({host})**; server side (node.js). On the (Angular) Front end, initialization is successful. The question is how to initialize it on the server side and will it work on the server side?
dfinity/agent": "~0.8.9"

**Comment by aymanfmustafa** [comment]
In Node JS you need to use `node-fetch`. Then initialize the HttpAgent with a custom fetch.  You could something like: 

`import` fetch from 'node-fetch;
const agent = new HttpAgent({host: "http://localhost:8000", fetch: fetch});`

**Comment by fury02** [comment]
Hi. Ok. But I still crash.
Code:

`
**import dfxConfig from '../../../dfx.json';**

// import {Actor, HttpAgent} from '@dfinity/agent';
// import {AuthClient} from "@dfinity/auth-client";
// import {Principal} from "@dfinity/principal";
// import {Ed25519KeyIdentity} from "@dfinity/identity";

**const HttpAgent = require('@dfinity/agent');
const fetch = require('node-fetch');**

**class ActorService {
    constructor() {
        const host = dfxConfig.networks_localhost.local.bind;
        const agent = new HttpAgent({host, fetch});
    }
}
export default ActorService;**
`

**Comment by fury02** [comment]
Oк. Sorry. This code worked.

```
constructor() {
    try {
      const identity = this.getNewIdentity();
      const host = 'http://127.0.0.1:8000';
      const agent = new HttpAgent({ host, fetch: typeof fetch });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
```
