### ISSUE TITLE
auth-client: login onSuccess async

### ISSUE THREAD

**Issue by peterpeterparker** [dfinity/agent-js#471]
**Is your feature request related to a problem? Please describe.**

According [README](https://github.com/dfinity/agent-js/tree/main/packages/auth-client) the function `login` should be use as follow:

```
authClient.login({
  onSuccess: async () => {
    // authClient now has an identity
  },
});
```

To the contrary, currently implemented, the function is [async](https://github.com/dfinity/agent-js/blob/579f8aa3fae946a9060bed39ff56c87151098c49/packages/auth-client/src/index.ts#L246) and the callback is [void](https://github.com/dfinity/agent-js/blob/579f8aa3fae946a9060bed39ff56c87151098c49/packages/auth-client/src/index.ts#L43). Therefore the proper example would be:

```
await authClient.login({
  onSuccess: () => {
    // authClient now has an identity
  },
});
```

Nevertheless, it would probably be for the best if both would support async, respectively:

```
await authClient.login({
  onSuccess: await () => {
    // authClient now has an identity
  },
});
```

**Describe the solution you'd like**

A description which match the implementation and I suggest also to have both function and callback support async.

**Comment by kritzcreek** [comment]
`login` already returns an `Promise`, why do we need the additional `onSuccess` and `onError` callbacks?

I'm wrapping the call up like this now, but it would be easier if I could just use the returned promise from `login`.
```js
  await new Promise((resolve, reject) => {
    authClient.login({
      onSuccess: resolve,
      onError: reject
    })
  })
```

**Comment by saikatdas0790** [comment]
Would you consider simplifying the login API so that the `authClient.login` just returns a `Promise<Identity>` and then we can just await the result. And for errors, we can wrap the `login` call in a try-catch.

Thoughts?
@krpeacock
