### ISSUE TITLE
Specified ingress_expiry not within expected range

### ISSUE THREAD

**Issue by earthgohan** [dfinity/agent-js#491]
User is unable to send transaction with dfinity httpagent. Is there any fix for this?

<img width="610" alt="Screenshot 2021-09-12 at 1 34 37 PM" src="https://user-images.githubusercontent.com/85003405/132979212-6ea41fd0-4ee4-4807-b7a6-781504c1d216.png">

OS: Windows
Browser: Google Chrome

**Comment by earthgohan** [comment]
Unable to reproduce the issue. AFAIK, it seems to be happening with devices with clock out of sync i.e users that have kept system clock few minutes more or less. Can you confirm if that is issue?

**Comment by krpeacock** [comment]
I think that could lead to this error, yes. I wonder what pattern we can recommend around it, because "user's device clock is accurate" shouldn't be a requirement for using the IC

**Comment by krpeacock** [comment]
The canonical new answer to this question is to use the `Agent.syncTime` method. https://agent-js.icp.xyz/agent/classes/HttpAgent.html#syncTime

**Comment by AryanEmpire26** [comment]
Your Ubuntu clock is not synchronized with system clock. Write this command in terminal of ubuntu timedatectl .This command will synchronize your ubuntu time with your system.  Make sure your system has correct time and date.

**Comment by Harshita-Negi** [comment]
If after resynchronizing the system clock, you are still facing the error then you can use the command sudo hwclock -s
