### ISSUE TITLE
agent request_id hashValue throws error

### ISSUE THREAD

**Issue by plitzenberger** [dfinity/agent-js#500]
When using `@dfinity/agent` within a shared npm module, authenticated calls to the backend fail with the error message:

```
Error: Attempt to hash a value of unsupported type: <canister_id>
```

The problem is that [the condition](https://github.com/dfinity/agent-js/blob/2fe3dd9/packages/agent/src/request_id.ts#L33):

```
else if (value instanceof Principal) {
    return hash(value.toUint8Array());
}
```

returns falsy when the value and the Class being compared reach across npm dependencies. It seems to be the case that we end up with two unique initializations of the Principal class. Javascript object equality is based on location in memory, not a structural comparison. [see here](https://forum.dfinity.org/t/mismatching-dfinity-agent-versions-can-cause-hashing-issues/7359)

**Comment by aramakme** [comment]
Close this one when handled as well -> https://github.com/dfinity/agent-js/issues/496
