### ISSUE TITLE
Notify the user interruption as an error

### ISSUE THREAD

**Issue by wewei** [dfinity/agent-js#525]
**Is your feature request related to a problem? Please describe.**
After calling `authClient.login(...)`, if the user closed the Internet Identity tab accidentally or intentionally, the app don't have an elegant way to catch it. The app may stuck at an "authenticating" stage.

**Describe the solution you'd like**
PR #526 
Let the `authClient` poll the `closed` state of `this._idpWindow`.
If it's closed by user, notify the caller through `option.onError`.

**Describe alternatives you've considered**
There're multiple work arounds for the app developers
1. Asking the user to refresh the page manually if it looks stuck
2. Keeping the "login" button available until the login succeeds (no "authenticating" stage)
3. Polling the Internet Identity window state through the `authClient._idpWindow` private property (ignore the TypeScript errors)

1 & 2 harm the UX, 3 is hack. It's better for `AuthClient` to encapsulate the polling.

There're also implementation options
1. Polling or messaging
  I suggest polling. An alternative solution is let II send a message on `beforeunload`, but it's not that reliable. The II window may crash by a browser failure or killed by the user, and there's no chance to signal `beforeunload`.
2. Notifying through `onError` or a new callback
  I prefer to reuse the `onError`. If the II window is closed by user, the authentication is interrupted. There should only be 2 terminal state of the auth process, authenticated (handled by `onSuccess`) or not (handled by `onError`). Adding a new callback adds unnecessary complexity to the caller's logic.

**Additional context**
My forum post about this issue
https://forum.dfinity.org/t/how-to-handle-user-interruption-in-internet-identity-auth/10675

**Comment by paulyoung** [comment]
I think I would prefer the second option of providing a callback (or `await`ing a `Promise`).

**Comment by wewei** [comment]
> I think I would prefer the second option of providing a callback (or `await`ing a `Promise`).

Indeed, I'd prefer the `AuthClient#login` to return a Promise. Like this
```typescript
(options: {
  identityProvider?: string | URL,
  maxTimeToLive?: bigint,
}) => Promise<Identity>
```

If we have 3 terminal state success, error, cancelled, it cannot be represented by a `Promise`.
However, that is a breaking change I don't think necessary for now.
