### ISSUE TITLE
IC0515: Certified state is not available yet. Please try again...

### ISSUE THREAD

**Issue by infu** [dfinity/agent-js#538]
**Describe the bug**

This error keeps showing in production (real IC network) 1 out of 300 requests.
"IC0515: Certified state is not available yet. Please try again..."
When you retry after a sec the request works. 

**Expected behavior**

It feels like agent-js should retry requests internally.

**Comment by nomeata** [comment]
This should only happen while a replica node is starting up and joining the subnet, right? I'm surprised it comes up so often.

Maybe the boundary node could even be smarter here?

**Comment by infu** [comment]
I just added sentry.io to our frontend. Will update you late with the exact count. So far it happened once to 3 different users for 1 hour.

**Comment by infu** [comment]
I will just post a screenshot of the two most prominent errors. You can see users, events, and when they happened on a 24h chart. Anyway, this issue is probably misplaced.
<img width="2168" alt="image" src="https://user-images.githubusercontent.com/24810/155692539-fc3f10f3-5a19-4e08-a1bd-9fbad70adfca.png">

**Comment by krpeacock** [comment]
Hopefully, this issue should be resolved by the new retry logic. I'll close for now
