### ISSUE TITLE
Float deserialization produces incorrect values

### ISSUE THREAD

**Issue by dansteren** [dfinity/agent-js#589]
**Describe the bug**
When deserializing canister responses, some float values are off by a small amount.

**To Reproduce**
1. Create a new rust canister with the following contents:
    ```rust
    #[ic_cdk_macros::query]
    async fn method() -> f32 {
        1245.678
    }
    ```
2. Update the corresponding candid file
    ```candid
    service : {
        "method": () -> (float32);
    }
    ```
3. With the replica running, run `dfx deploy`
4. Call the canister with `dfx canister call test method`
5. Note that from dfx the return value is correct: `(1245.678 : float32)`
6. Open the Candid UI in your browser (URL will vary) and click the "Call" button to call the method.
7. Note that the return value doesn't match the value returned from your canister (`1245.678`) but is instead slightly off (`1245.677978515625`)

**Expected behavior**
When calling the canister using the JS agent you should get back `1245.678`, the precise value sent from the canister, just like the rust agent.

**Screenshots**
Screenshot of the candid UI returning an incorrect value:
![Screenshot from 2022-07-06 14-21-58](https://user-images.githubusercontent.com/5455419/177636528-aebaa1f1-d2e9-4e20-99db-d392c7b8fbfa.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 22.04
- Browser: Brave Version 1.40.113 Chromium: 103.0.5060.114 (Official Build) (64-bit)

**Comment by chenyan-dfinity** [comment]
Close as it's working as expected.

You lose precision when converting a decimal number into binary. For example, there is no way to represent 0.1 in base 2. The fact that dfx decoded the floating point number to be exactly the same as your original input is accidental. As a result, you should never use `==` to compare two floating point numbers, it almost never works.
