### ISSUE TITLE
Expose idb AUTH_DB_NAME and OBJECT_STORE_NAME constants

### ISSUE THREAD

**Issue by peterpeterparker** [dfinity/agent-js#610]
## Feature request

It would be cool if both constants `AUTH_DB_NAME` and `OBJECT_STORE_NAME` from `auth-client` [db.ts](https://github.com/dfinity/agent-js/blob/1cafb382a7dbcfd4fc5f8e32a5710bfca5c8011e/packages/auth-client/src/db.ts#L6) would be exposed for the consumer of the lib.

This is particularly interesting - for maintainability reason - for those who want to read the delegation and identity information that are saved in indexeddb.

**Comment by krpeacock** [comment]
Can do! For fun, you can also just construct the [IdbStorage](https://erxue-5aaaa-aaaab-qaagq-cai.ic0.app/auth-client/classes/IdbStorage.html) interface with default options and get and set those values freely

**Comment by peterpeterparker** [comment]
@krpeacock that's an excellent idea! I will try tomorrow, if it works it's way better than exposing the constant.

**Comment by peterpeterparker** [comment]
@krpeacock indeed using `IdbStorage` in our web worker would work and therefore make this feature request unuseful.

Being said, while replacing our custom code in web worker with agent-js and this class, I noticed the two following issues for which I provided PRs:

- https://github.com/dfinity/agent-js/pull/611
- https://github.com/dfinity/agent-js/pull/612

Let me know if these make sense to you too. Once merged, it would be cool if you could release a new version because we will need such improvements to integrate the last version of agent-js in NNS-dapp PR [#1247](https://github.com/dfinity/nns-dapp/pull/1247).
