### ISSUE TITLE
Nat32

### ISSUE THREAD

**Issue by maxm224** [dfinity/agent-js#631]
**Describe the bug**
When defining a nat32 in motoko, the type generated in did.d.ts is number. Which can have 64bits. This causes errors to be thrown when passing the number to the motoko function. Maybe it would be better to generate the bigint type for nat32 numbers. This would enable us to make sure we pass a 32 bit (BigInt.asUintN(32, number))

**To Reproduce**

1. Declare a nat32 as a function argument
2. Call the function from the frontend

**Comment by krpeacock** [comment]
@chenyan-dfinity @rvanasa what do you think? I have no issue with the reasoning, but note this would be a breaking change

**Comment by chenyan-dfinity** [comment]
The current behavior is working as expected:
* On the JS side, we check the number range before sending the data to canister: https://github.com/dfinity/agent-js/blob/main/packages/candid/src/idl.ts#L697. So the error you get should be from the JS side, not from Motoko side.
* We actually allow users to pass either number or bigint to a `NatXX` type, and will check the range in both cases.
* One minor correction: number type in JS can only represent 53bits of integers, not 64bits.
