### ISSUE TITLE
Generated agent code broken in Node.js

### ISSUE THREAD

**Issue by dansteren** [dfinity/agent-js#656]
**Describe the bug**

Node.js requires a host to be specified when creating an actor using the `createActor` method in the generated agent. However, the code generated by `dfx generate` doesn't specify a host and therefore breaks as soon as it is imported.

**To Reproduce**

1. Create a simple canister in the language of your choice
1. Generate an agent by running `dfx generate`. This will generate among other things an index.js file containing the line `export const my_canister_name = createActor(canisterId);`
1. Use the generated agent in a simple node.js file. For example:

    ```js
    import { createActor } from "../dfx_generated";

    console.log("We break before we even get here.");

    const hello_world_canister = createActor("rrkah-fqaaa-aaaaa-aaaaq-cai", {
      agentOptions: {
        host: "http://127.0.0.1:8000",
      },
    });
    ```

1. Run the script with node
1. Note that this results in the following error:

    ```error
    hello_world/node_modules/@dfinity/agent/lib/cjs/agent/http/index.js:141
                    throw new Error('Must specify a host to connect to.');
                          ^
    Error: Must specify a host to connect to.
        at new HttpAgent (hello_world/node_modules/@dfinity/agent/lib/cjs/agent/http/index.js:141:23)
    ```

**Expected behavior**

I should be able to import the createActor statement, or the actor directly without everything breaking.

**Desktop (please complete the following information):**

- Node v18.1.0
- dfx v0.11.0
- JS Agent v0.11.1

**Additional context**

There is an open forum post with additional details. See https://forum.dfinity.org/t/generated-declarations-in-node-js-environment-break/12686

**Comment by dansteren** [comment]
As a workaround you can manually comment out the last line in the generated index.js, however this is just a bandaid solution.

**Comment by dansteren** [comment]
Also, this is closely related to https://github.com/dfinity/sdk/issues/2240.

**Comment by krpeacock** [comment]
This has been resolved by -https://github.com/dfinity/sdk/commit/32c168ec75ca4ca8dd409db59e4b2d78444bbfb5

To use the feature in your code, add the setting of

canister -> declarations -> "node_compatibility": true
