### ISSUE TITLE
Can't use the new package `@dfinity/identity-secp256k1`

### ISSUE THREAD

**Issue by harshbaz** [dfinity/agent-js#666]
**Describe the bug**
Trying to import `Secp256k1KeyIdentity` from the new separate package results in an error.

**To Reproduce**
Try importing `import { Secp256k1KeyIdentity } from '@dfinity/identity-secp256k1';` in a `ts` file.
and you should see an error thrown by typescript about an invalid import.

And, there's no lib folder that package json is referring to:

![image](https://user-images.githubusercontent.com/106158714/207582008-48c4960a-152f-4bf6-98c6-09e8e1a43bc3.png)

**Expected behavior**
I should be able to import it

**Comment by krpeacock** [comment]
Thanks for calling this to my attention. I know exactly what went wrong, and I'll have a fix released today
