### ISSUE TITLE
Identity generated by `fromSeedPhrase` is not compatible with actor created

### ISSUE THREAD

**Issue by harshbaz** [dfinity/agent-js#679]
**Describe the bug**
Generating an identity from `fromSeedPhrase()` is not usable when creating an actor.

**To Reproduce**
Code to generate identity: 
```
import { Secp256k1KeyIdentity } from '@dfinity/identity-secp256k1';

// Completely insecure seed phrase. Do not use for any purpose other than testing.
const seed = 'test test test test test test test test test test test test';

export const identityFromSeed = async (phrase) => {
	return Secp256k1KeyIdentity.fromSeedPhrase(phrase);
};

export const identity = identityFromSeed(seed);
```

Code to use the above generated identity:
```
import {identity} from ./identity.ts
...
const agent = new HttpAgent({ host: 'http://0.0.0.0:4943', fetch, identity });
```

Results in an error:
```
Error: input is invalid type
 ❯ Sha256.update ../../node_modules/js-sha256/src/sha256.js:177:19
 ❯ Secp256k1KeyIdentity.sign ../../node_modules/@dfinity/identity-secp256k1/src/secp256k1.ts:204:10
 ❯ Secp256k1KeyIdentity.transformRequest ../../node_modules/@dfinity/agent/src/auth.ts:94:32
 ❯ HttpAgent.call ../../node_modules/@dfinity/agent/src/agent/http/index.ts:331:4
 ❯ caller ../../node_modules/@dfinity/agent/src/actor.ts:376:26
```

**Expected behavior**
Generated identity should work as a normal identity with agentJs.

**Screenshots**
None

**Desktop (please complete the following information):**

- OS: Mac
- Browser Chrome
- DFX: 0.12.0

**Comment by krpeacock** [comment]
@harshbaz I have attempted to reproduce this issue here: https://github.com/krpeacock/secp-identity-reproduction. However, I am not encountering the issue.

I am using node `v18.12.1` (for lower versions, it may require a fetch polyfill) and npm `8.19.2`

**Comment by krpeacock** [comment]
Perhaps your issue is with the `host`, which typically would be pointing at `"http://127.0.0.1:4943"` locally.

**Comment by harshbaz** [comment]
@krpeacock Thank you for the minimal reproduction repository. The error was due to wrong environment in `vitest`. Thanks!
