### ISSUE TITLE
Requests blocked by CORS policy in 0.15.2

### ISSUE THREAD

**Issue by harshbaz** [dfinity/agent-js#683]
**Describe the bug**
All requests to canisters are failing with this error on 0.15.2:
<img width="425" alt="image" src="https://user-images.githubusercontent.com/106158714/215009989-f3621c7e-04c9-4261-a215-ced6caa9f4f9.png">

**To Reproduce**
Upgrade to `0.15.2` version for `@dfinity/*` packages.

**Desktop (please complete the following information):**

- OS: Macos
- Browser: Chrome
- Version v109
- DFX SDK: v0.12.1

**Comment by jaesharma** [comment]
Facing same issue. i'm using @dfinity/assets to list assets of canister. but getting CORS error.
@dfinity/agent: 0.15.2
@dfinity/assets: 0.15.2

update:
downgrading assets @dfinity/agent version to 0.14.1 solved the issue for me.

**Comment by harshbaz** [comment]
> downgrading @dfinity/agent version to 0.14.1 solved the issue for me.

For me it's only the version `0.15.2` that's giving the CORS error. `0.15.1` is fine. Seems to be related to #672.

**Comment by ocluf** [comment]
Same issue here downgrading to 0.15.1 fixes it. Looks like this part of the changelog in 0.15.2

Introduces X-IC-Request-ID header to more easily identify retried requests. Also uses a standard Headers constructor to manage headers. 

Seems like the proxy in dfx needs to be updated to allow the header not agent-js.

**Comment by krpeacock** [comment]
Interesting - I wonder if it was the headers structure, or the new one. I'll investigate and release a fix early next week

**Comment by krpeacock** [comment]
Thanks for calling this out. I've rolled back the header and released 0.15.3. I'll coordinate with ICX Proxy and dfx before revisiting
