### ISSUE TITLE
BLS verify not being forwarded?

### ISSUE THREAD

**Issue by sea-snake** [dfinity/agent-js#760]
Looking at the following line, it looks like a BLS verify is only used once but not for subsequent recursive calls.
https://github.com/dfinity/agent-js/blob/ac767561bd50882734c75572c7a0c36b663ffcf7/packages/agent/src/polling/index.ts#L63C9-L63C9

**Comment by Perlets9** [comment]
Hey @sea-snake , yes I have the same problem with the BLS verify, I mentioned this on: https://github.com/dfinity/agent-js/pull/745

**Comment by krpeacock** [comment]
Sorry for the inconvenience - the BLS verify feature is going to be deprecated and replaced soon with a native JS verification strategy from `@noble/curves`
