### ISSUE TITLE
BLS-verify bundling issue

### ISSUE THREAD

**Issue by Gekctek** [dfinity/agent-js#773]
I am trying to integrate the bls-verify package into a raw js file for some WebGL unity project for ICP.NET
The issue I am having is that I am doing `npx esbuild --bundle src/index.ts --outfile=dist/index.js --platform=browser` to bundle up the package to include as raw js, but the issue is that it breaks because all the files in `packages/bls-verify/src/vendor/amcl-js/src` are not included except for ctx.js. It seems to be an issue because of the dynamic loading of the other files like aes.js. When it tries to load them it breaks
How do you guys handle this?

**Comment by krpeacock** [comment]
Sorry for the inconvenience - the BLS verify feature is going to be deprecated and replaced soon with a native JS verification strategy from `@noble/curves`
