### ISSUE TITLE
Fix missing JSdoc

### ISSUE THREAD

**Issue by peterpeterparker** [dfinity/agent-js#811]
**Is your feature request related to a problem? Please describe.**

PR changes are hard to read because of repeated warning regarding the missing documentation.

>  Check warning on line 1535 in packages/candid/src/idl.ts
>  GitHub Actions / test (8.8.4, release-0.16, 20)
>  
>  Missing JSDoc @param "x" description       

<img width="1536" alt="Capture d’écran 2023-12-11 à 08 48 52" src="https://github.com/dfinity/agent-js/assets/16886711/db1616b6-d322-42d7-84ed-d6e1e9223dde">

**Describe the solution you'd like**

Add missing documentation or disable related CI job.

**Comment by krpeacock** [comment]
I've put this off long enough. Issue accepted 😄
